[env]
# TERM = "tmux-256color"
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/rose-pine-dawn.toml"
]

[window]
startup_mode = "Fullscreen"
decorations_theme_variant = "Light"

[font]
size = 8
normal = { family = "JetBrainsMono NFM", style = "Regular" }
bold = { family = "JetBrainsMono NFM", style = "Bold" }
italic = { family = "JetBrainsMono NFM", style = "Italic" }
bold_italic = { family = "JetBrainsMono NFM", style = "Bold Italic" }

[mouse]
hide_when_typing = true
